const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/lNyLSOKMMeUPr1RsL4KcRuIXwHt.jpg",
      genre_ids: [878, 28],
      id: 580489,
      original_language: "en",
      original_title: "Venom: Let There Be Carnage",
      overview:
        "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
      popularity: 7272.955,
      poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
      release_date: "2021-09-30",
      title: "Venom: Let There Be Carnage",
      video: false,
      vote_average: 7,
      vote_count: 941,
    },
    {
      adult: false,
      backdrop_path: "/2cdrhlf3hvvueGyQDx0u8jpWvQR.jpg",
      genre_ids: [27, 53],
      id: 610253,
      original_language: "en",
      original_title: "Halloween Kills",
      overview:
        "Minutes after Laurie Strode, her daughter Karen and granddaughter Allyson left masked monster Michael Myers caged and burning in Laurie's basement, Laurie is rushed to the hospital with life-threatening injuries, believing she finally killed her lifelong tormentor. But when Michael manages to free himself from Laurie's trap, his ritual bloodbath resumes. As Laurie fights her pain and prepares to defend herself against him, she inspires all of Haddonfield to rise up against their unstoppable monster. The Strode women join a group of other survivors of Michael's first rampage who decide to take matters into their own hands, forming a vigilante mob that sets out to hunt Michael down, once and for all.",
      popularity: 3809.567,
      poster_path: "/qmJGd5IfURq8iPQ9KF3les47vFS.jpg",
      release_date: "2021-10-14",
      title: "Halloween Kills",
      video: false,
      vote_average: 7.5,
      vote_count: 547,
    },
    {
      adult: false,
      backdrop_path: "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
      genre_ids: [35, 28, 12, 878],
      id: 550988,
      original_language: "en",
      original_title: "Free Guy",
      overview:
        "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
      popularity: 3360.83,
      poster_path: "/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
      release_date: "2021-08-11",
      title: "Free Guy",
      video: false,
      vote_average: 7.8,
      vote_count: 2986,
    },
    {
      adult: false,
      backdrop_path: "/gOglaWhGx246MvzpnYMZ7HiBkiK.jpg",
      genre_ids: [28, 12, 18, 878],
      id: 438631,
      original_language: "en",
      original_title: "Dune",
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 2780.144,
      poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      release_date: "2021-09-15",
      title: "Dune",
      video: false,
      vote_average: 8.1,
      vote_count: 1858,
    },
    {
      adult: false,
      backdrop_path: "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
      genre_ids: [878, 28],
      id: 335983,
      original_language: "en",
      original_title: "Venom",
      overview:
        "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
      popularity: 2142.138,
      poster_path: "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
      release_date: "2018-09-28",
      title: "Venom",
      video: false,
      vote_average: 6.8,
      vote_count: 11890,
    },
    {
      adult: false,
      backdrop_path: "/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg",
      genre_ids: [28, 35, 12],
      id: 772436,
      original_language: "es",
      original_title: "Matando Cabos 2: La Máscara del Máscara",
      overview:
        'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
      popularity: 1819.79,
      poster_path: "/jxdKa1467pktAILLbfw6kZyQlbW.jpg",
      release_date: "2021-10-01",
      title: "Matando Cabos 2: La Máscara del Máscara",
      video: false,
      vote_average: 8.1,
      vote_count: 44,
    },
    {
      adult: false,
      backdrop_path: "/kTOheVmqSBDIRGrQLv2SiSc89os.jpg",
      genre_ids: [16, 35, 10751],
      id: 639721,
      original_language: "en",
      original_title: "The Addams Family 2",
      overview:
        "The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters.",
      popularity: 1877.493,
      poster_path: "/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg",
      release_date: "2021-10-01",
      title: "The Addams Family 2",
      video: false,
      vote_average: 7.6,
      vote_count: 356,
    },
    {
      adult: false,
      backdrop_path: "/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg",
      genre_ids: [28, 12],
      id: 568620,
      original_language: "en",
      original_title: "Snake Eyes: G.I. Joe Origins",
      overview:
        "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
      popularity: 1864.934,
      poster_path: "/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg",
      release_date: "2021-07-22",
      title: "Snake Eyes: G.I. Joe Origins",
      video: false,
      vote_average: 6.9,
      vote_count: 703,
    },
    {
      adult: false,
      backdrop_path: "/ux6gkGSKNFtp2NFYxwYFxVWdnGa.jpg",
      genre_ids: [80, 18, 53],
      id: 874948,
      original_language: "tr",
      original_title: "Kin",
      overview:
        "Ahead of a promotion, a police chief becomes entangled in a deadly incident and uncovers an intrigue fueled by grudge that threatens his colleagues.",
      popularity: 1492.253,
      poster_path: "/xSqtHT2DWbWBZ4dUvvMs6z1OfFK.jpg",
      release_date: "2021-10-08",
      title: "Grudge",
      video: false,
      vote_average: 6.5,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: "/owraiceOKtSOa3t8sp3wA9K2Ox6.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 703771,
      original_language: "en",
      original_title: "Deathstroke: Knights & Dragons - The Movie",
      overview:
        "The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.",
      popularity: 1457.644,
      poster_path: "/vFIHbiy55smzi50RmF8LQjmpGcx.jpg",
      release_date: "2020-08-04",
      title: "Deathstroke: Knights & Dragons - The Movie",
      video: false,
      vote_average: 7,
      vote_count: 283,
    },
    {
      adult: false,
      backdrop_path: "/4KpNHvQIjyg1YFovRAoUXoFrGnR.jpg",
      genre_ids: [16, 12],
      id: 662708,
      original_language: "ja",
      original_title: "劇場版ポケットモンスター ココ",
      overview:
        "In the Forest of Okoya, Koko is a feral child who has been raised as a Pokémon by the Mythical Pokémon Zarude. Koko has grown up never doubting that he is a Pokémon even though he can't really use any sort of moves. Ash Ketchum and Pikachu meet Koko and help him protect the Great Tree from the crooked scientist Dr. Zed.",
      popularity: 1309.101,
      poster_path: "/vGcHyV9s1N2I7bJLSBODvqHTYLL.jpg",
      release_date: "2020-12-25",
      title: "Pokémon the Movie: Secrets of the Jungle",
      video: false,
      vote_average: 7.4,
      vote_count: 48,
    },
    {
      adult: false,
      backdrop_path: "/7h5WAPAcUzOWpp2jrwHBB48790j.jpg",
      genre_ids: [16, 28],
      id: 843241,
      original_language: "ja",
      original_title: "劇場版 七つの大罪 光に呪われし者たち",
      overview:
        'With the help of the "Dragon Sin of Wrath" Meliodas and the worst rebels in history, the Seven Deadly Sins, the "Holy War", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the "Lion Sin of Pride" Escanor\'s life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.',
      popularity: 1428.137,
      poster_path: "/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg",
      release_date: "2021-07-02",
      title: "The Seven Deadly Sins: Cursed by Light",
      video: false,
      vote_average: 8.4,
      vote_count: 179,
    },
    {
      adult: false,
      backdrop_path: "/q4h2ZbhHKhnWvrrqzcjT778zlbn.jpg",
      genre_ids: [16, 878, 14, 28],
      id: 831405,
      original_language: "en",
      original_title: "Injustice",
      overview:
        "When Lois Lane is killed, an unhinged Superman decides to take control of the Earth. Determined to stop him, Batman creates a team of freedom-fighting heroes. But when superheroes go to war, can the world survive?",
      popularity: 1350.445,
      poster_path: "/lNRdCfVcjLs2LhO1Vb5rgnHV4JW.jpg",
      release_date: "2021-10-09",
      title: "Injustice",
      video: false,
      vote_average: 8.1,
      vote_count: 224,
    },
    {
      adult: false,
      backdrop_path: "/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg",
      genre_ids: [14, 12, 35],
      id: 589754,
      original_language: "ru",
      original_title: "Последний богатырь: Корень зла",
      overview:
        "Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.",
      popularity: 1149.589,
      poster_path: "/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg",
      release_date: "2021-01-01",
      title: "The Last Warrior: Root of Evil",
      video: false,
      vote_average: 7.3,
      vote_count: 57,
    },
    {
      adult: false,
      backdrop_path: "/hrzoy8vvUrxQixOM11pwW9AX7Bu.jpg",
      genre_ids: [80, 18],
      id: 524369,
      original_language: "en",
      original_title: "The Many Saints of Newark",
      overview:
        "Young Anthony Soprano is growing up in one of the most tumultuous eras in Newark, N.J., history, becoming a man just as rival gangsters start to rise up and challenge the all-powerful DiMeo crime family. Caught up in the changing times is the uncle he idolizes, Dickie Moltisanti, whose influence over his nephew will help shape the impressionable teenager into the all-powerful mob boss, Tony Soprano.",
      popularity: 1002.557,
      poster_path: "/1UkbPQspPbq1FPbFP4VV1ELCfSN.jpg",
      release_date: "2021-09-22",
      title: "The Many Saints of Newark",
      video: false,
      vote_average: 6.8,
      vote_count: 136,
    },
    {
      adult: false,
      backdrop_path: "/vkIJ2QgcKMJRvi6pBW4Tr2kgLdy.jpg",
      genre_ids: [80, 53],
      id: 637534,
      original_language: "fr",
      original_title: "BAC Nord",
      overview:
        "A police brigade working in the dangerous northern neighborhoods of Marseille, where the level of crime is higher than anywhere else in France.",
      popularity: 1029.486,
      poster_path: "/nLanxl7Xhfbd5s8FxPy8jWZw4rv.jpg",
      release_date: "2021-08-18",
      title: "The Stronghold",
      video: false,
      vote_average: 7.7,
      vote_count: 440,
    },
    {
      adult: false,
      backdrop_path: "/dNQTwFmEj1b5SktT8oWGH5Cunlx.jpg",
      genre_ids: [28, 12, 14],
      id: 566525,
      original_language: "en",
      original_title: "Shang-Chi and the Legend of the Ten Rings",
      overview:
        "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
      popularity: 1060.576,
      poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
      release_date: "2021-09-01",
      title: "Shang-Chi and the Legend of the Ten Rings",
      video: false,
      vote_average: 7.8,
      vote_count: 1306,
    },
    {
      adult: false,
      backdrop_path: "/umAoDwLZMBrYeCDfbJYFRMuXWAr.jpg",
      genre_ids: [878],
      id: 681887,
      original_language: "en",
      original_title: "Cosmic Sin",
      overview:
        "In the year 2524, four centuries after humans started colonizing the outer planets, retired General James Ford gets called back into service when a hostile alien fleet attacks soldiers on a remote planet. The threat against mankind soon escalates into an interstellar war as Ford and a team of elite soldiers try to stop the imminent attack before it's too late.",
      popularity: 986.724,
      poster_path: "/6Wm7P6y22UZA40QuPYHyWyJ6leI.jpg",
      release_date: "2021-03-12",
      title: "Cosmic Sin",
      video: false,
      vote_average: 4.5,
      vote_count: 343,
    },
    {
      adult: false,
      backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
      genre_ids: [28, 12, 14],
      id: 436969,
      original_language: "en",
      original_title: "The Suicide Squad",
      overview:
        "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
      popularity: 1049.845,
      poster_path: "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
      release_date: "2021-07-28",
      title: "The Suicide Squad",
      video: false,
      vote_average: 7.8,
      vote_count: 4460,
    },
    {
      adult: false,
      backdrop_path: "/Aj9yZcNnGmOmOBzKskeffLWk65j.jpg",
      genre_ids: [878, 53, 9648],
      id: 675319,
      original_language: "en",
      original_title: "Zone 414",
      overview:
        "In the near future on a colony of state-of-the-art robots, a private investigator is hired by the colony's creator to bring his missing daughter home.",
      popularity: 961.188,
      poster_path: "/wIm5S6Blkb0qDMTGVu80VWSrQV1.jpg",
      release_date: "2021-09-03",
      title: "Zone 414",
      video: false,
      vote_average: 6,
      vote_count: 62,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

// data.results.forEach((val) => {
//   console.log(val.results.title);
// });

const newArr = data.results;
// console.log(newArr);

// newArr.forEach((val) => {
//   console.log(val.title);
// });

console.log(`${newArr}`);
